### ISSUE TITLE
preferences

### ISSUE THREAD

**Issue by crogersdev** [creedrogers/CuedSpeech#3]
need to have the ability to save preferences
- change mnemonic to whatever the user wants (please retain mnemonic highlighting per issue #2)
- remember which card you were on as you switch back and forth between vowels/consonants and other areas of the app
- ???  what else???

**Comment by tholmes** [comment]
I can help out with the preferences, if you'd like?

**Comment by crogersdev** [comment]
Yeah, that could work.

Bullet point 2 is taken care of, I just haven't pushed it up.

Bullet point 1 is kind of interesting.  Each hand position corresponds to vowels or consonants.  A mnemonic helps you remember which ones.  For hand position 1, which is what you use for /d/, /p/ and /zh/, I have made the default "deep treasure."  /d/, /p/ and the /zh/ part of 'treasure.'  If someone wanted to change that mnemonic to a different phrase they might remember better, I not only want to be able to store that but also highlight the /d/, /p/, and /zh/ in the mnemonic.  

Let me push up changes tonight and I will notify you.  Then you'll have the most recent copy of the code and you can build it and get it running (a task in and of itself) and see what I'm talking about.

**Comment by tholmes** [comment]
Sounds good, I will wait for you to push that code up and then I can try out the app to get familiar with it.

**Comment by crogersdev** [comment]
Tim,

Try doing a pull and importing the project into Android Studio.  Let me know if it doesn't build.  I'm wondering how much of the *.xml, *.iml, and other configuration files need to be tracked.  I added everything into this latest commit, so it's very specific to my version of Android Studio, gradle, and such.

**Comment by tholmes** [comment]
Code built with no problems. The app looks GREAT!
After looking at the app and reading up a bit more on what cued-speech is, I think I have a good understanding of what you were talking about with not only storing a custom mnemonic, but also retain highlighting of the phonemes.
I'm going to spend some time studying the code to get a better understanding of how you're doing what you're doing, and then see where where I go from there. I'll draw up some designs and send them to you and see what we can come up with.

**Comment by crogersdev** [comment]
breaking these up into individual issues and closing this one
