### ISSUE TITLE
Add Gitignore file

### ISSUE THREAD

**Issue by tholmes** [creedrogers/CuedSpeech#6]
I see that you have a `.gitignore_old` file. Haven't really looked to see what was in in, but I just happened to notice that after I built the app and got it running there were several files that "my" environment changed. and a couple new files that my environment added. Below is the screenshot. I wonder if we should add a gitigore file to ignore these files - they seem pretty environment-dependent. 

I can create a gitignore and add these files, do some testing to make sure that they aren't necessary to have in the repo. If this be the case, I can send you a pull request with the gitignore changes, if that sounds alright to you.

![image](https://cloud.githubusercontent.com/assets/3581187/16175525/1596a420-35ae-11e6-8e2b-f33190e16872.png)

**Comment by crogersdev** [comment]
I will check out your remote branch and see how it works.  You're exactly right - the .gitignore_old file was meant to do exactly this, but when I cloned a new copy of the repo on a new computer I had, it wouldn't build.  Gave me some gradle problems.  Anticipating that you'd have the same problems, I added the project settings back in by renaming the .gitignore file to .gitignore_old, thinking it was better to change a dozen or so project settings files than it was to have you try and figure out how to fix a build problem.

If you've been able to test this gitignore file in new clone, which is what I will test, then we'll merge it in with master.

Great work!  :D
